export const GET_CALENDAR_DATE_LOGS = 'GET_CALENDAR_DATE_LOGS';
export const ADD_CALENDAR_DATE_LOG = 'ADD_CALENDAR_DATE_LOG';
export const RESET_CALENDAR_DATE_LOGS = 'RESET_CALENDAR_DATE_LOGS';
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE';
export const CALENDAR_ERROR = 'CALENDAR_ERROR';