export const TOGGLE_HOME_MENU = 'TOGGLE_HOME_MENU';
export const TOGGLE_CLIENTS_MENU = 'TOGGLE_CLIENTS_MENU';
export const TOGGLE_TASKS_MENU = 'TOGGLE_TASKS_MENU';
export const TOGGLE_CALENDAR_MENU = 'TOGGLE_CALENDAR_MENU';