export const TOGGLE_HOME_MENU = 'TOGGLE_HOME_MENU';
export const TOGGLE_CLIENTS_MENU = 'TOGGLE_CLIENTS_MENU';
export const TOGGLE_TASKS_MENU = 'TOGGLE_TASKS_MENU';
export const TOGGLE_CALENDAR_MENU = 'TOGGLE_CALENDAR_MENU';

export const TOGGLE_CREATE_COMPANY = 'TOGGLE_CREATE_COMPANY';
export const TOGGLE_EDIT_COMPANY = 'TOGGLE_EDIT_COMPANY';
export const RESET_COMPANY_STATE = 'RESET_COMPANY_STATE';

export const TOGGLE_EDIT_CLIENT = 'TOGGLE_EDIT_CLIENT';
export const RESET_EDIT_CLIENT = 'RESET_EDIT_CLIENT';